export type ColorProps = 'error' | 'grey' | 'info' | 'primary' | 'secondary' | 'success' | 'warning'

export type ShadeProps =
  | 'xxsoft'
  | 'xsoft'
  | 'soft'
  | 'light'
  | 'highlight'
  | 'main'
  | 'medium'
  | 'dark'
  | 'xdark'
  | 'xxdark'
  | 'contrastText'
  | '50'
  | '100'
  | '200'
  | '300'
  | '400'
  | '500'
  | '600'
  | '700'
  | '800'
  | '900'
